// Helpers
// ---------------------------------------------------
const compose2 = (f, g) => (...args) => f(g(...args))
const compose = (...fns) => fns.reduce(compose2);
// toString: * -> String
const toString = (a) => '' + a
// tl : String -> String
const tl = (a) => a.toLowerCase()
// merge : Array Array -> Object
const merge = (keys, values) => keys.reduce((acc, k, i) => Object.assign(acc, {[k]: values[i]}), {})

// Main
// ---------------------------------------------------
const ATTRS = ['symbol', 'name', 'symbol_native', 'code', 'name_plural', 'decimal_digits', 'rounding', 'integer_separatod', 'decimal_separator', 'symbol_left', 'space_amount_symbol']
const CurrencyFormats = [
// symbol, name, symbol_native, code, name_plural, decimal_digits, rounding, integer_separatod, decimal_separator,symbol_left, space_amount_symbol
  ['$','US Dollar','$','USD','US dollars',2,0,',','.',true,false],
  ['CA$','Canadian Dollar','$','CAD','Canadian dollars',2,0,',','.',true,false],
  ['€','Euro','€','EUR','euros',2,0,' ',',',false,true],
  ['AED','United Arab Emirates Dirham','د.إ.‏','AED','UAE dirhams',2,0,',','.',true,true],
  ['Af','Afghan Afghani','؋','AFN','Afghan Afghanis',0,0,',','.',true,false],
  ['ALL','Albanian Lek','Lek','ALL','Albanian lekë',0,0,'.',',',false,false],
  ['AMD','Armenian Dram','դր.','AMD','Armenian drams',0,0,',','.',false,true],
  ['AR$','Argentine Peso','$','ARS','Argentine pesos',2,0,'.',',',true,true],
  ['AU$','Australian Dollar','$','AUD','Australian dollars',2,0,',','.',true,false],
  ['man.','Azerbaijani Manat','ман.','AZN','Azerbaijani manats',2,0,' ',',',false,true],
  ['KM','Bosnia-Herzegovina Convertible Mark','KM','BAM','Bosnia-Herzegovina convertible marks',2,0,'.',',',false,true],
  ['Tk','Bangladeshi Taka','৳','BDT','Bangladeshi takas',2,0,',','.',true,true],
  ['BGN','Bulgarian Lev','лв.','BGN','Bulgarian leva',2,0,' ',',',false,true],
  ['BD','Bahraini Dinar','د.ب.‏','BHD','Bahraini dinars',3,0,',','.',true,true],
  ['FBu','Burundian Franc','FBu','BIF','Burundian francs',0,0,',','.',false,false],
  ['BN$','Brunei Dollar','$','BND','Brunei dollars',2,0,'.',',',true,false],
  ['Bs','Bolivian Boliviano','Bs','BOB','Bolivian bolivianos',2,0,'.',',',true,true],
  ['R$','Brazilian Real','R$','BRL','Brazilian reals',2,0,'.',',',true,true],
  ['BWP','Botswanan Pula','P','BWP','Botswanan pulas',2,0,',','.',true,false],
  ['BYR','Belarusian Ruble','BYR','BYR','Belarusian rubles',0,0,' ',',',false,true],
  ['BZ$','Belize Dollar','$','BZD','Belize dollars',2,0,',','.',true,false],
  ['CDF','Congolese Franc','FrCD','CDF','Congolese francs',2,0,',','.',false,false],
  ['CHF','Swiss Franc','CHF','CHF','Swiss francs',2,0.05,'\'','.',false,true],
  ['CL$','Chilean Peso','$','CLP','Chilean pesos',0,0,'.',',',true,true],
  ['CN¥','Chinese Yuan','CN¥','CNY','Chinese yuan',2,0,',','.',true,false],
  ['CO$','Colombian Peso','$','COP','Colombian pesos',0,0,'.',',',true,true],
  ['₡','Costa Rican Colón','₡','CRC','Costa Rican colóns',0,0,'.',',',true,false],
  ['CV$','Cape Verdean Escudo','CV$','CVE','Cape Verdean escudos',2,0,',','.',true,false],
  ['Kč','Czech Republic Koruna','Kč','CZK','Czech Republic korunas',2,0,' ',',',false,true],
  ['Fdj','Djiboutian Franc','Fdj','DJF','Djiboutian francs',0,0,',','.',false,false],
  ['Dkr','Danish Krone','kr','DKK','Danish kroner',2,0,'',',',false,true],
  ['RD$','Dominican Peso','RD$','DOP','Dominican pesos',2,0,',','.',true,false],
  ['DA','Algerian Dinar','د.ج.‏','DZD','Algerian dinars',2,0,',','.',true,true],
  ['Ekr','Estonian Kroon','kr‏','EEK','Estonian kroons',2,0,',','.',true,true],
  ['EGP','Egyptian Pound','ج.م.‏','EGP','Egyptian pounds',2,0,',','.',true,true],
  ['Nfk','Eritrean Nakfa','Nfk','ERN','Eritrean nakfas',2,0,',','.',false,false],
  ['Br','Ethiopian Birr','Br','ETB','Ethiopian birrs',2,0,',','.',true,false],
  ['£','British Pound Sterling','£','GBP','British pounds sterling',2,0,',','.',true,false],
  ['GEL','Georgian Lari','GEL','GEL','Georgian laris',2,0,' ',',',false,true],
  ['GH₵','Ghanaian Cedi','GH₵','GHS','Ghanaian cedis',2,0,',','.',true,false],
  ['FG','Guinean Franc','FG','GNF','Guinean francs',0,0,',','.',false,false],
  ['GTQ','Guatemalan Quetzal','Q','GTQ','Guatemalan quetzals',2,0,',','.',true,false],
  ['HK$','Hong Kong Dollar','$','HKD','Hong Kong dollars',2,0,',','.',true,false],
  ['HNL','Honduran Lempira','L','HNL','Honduran lempiras',2,0,',','.',true,true],
  ['kn','Croatian Kuna','kn','HRK','Croatian kunas',2,0,'.',',',false,true],
  ['Ft','Hungarian Forint','Ft','HUF','Hungarian forints',0,0,' ',',',false,true],
  ['Rp','Indonesian Rupiah','Rp','IDR','Indonesian rupiahs',0,0,'.',',',true,false],
  ['₪','Israeli New Sheqel','₪','ILS','Israeli new sheqels',2,0,',','.',true,true],
  ['Rs','Indian Rupee','টকা','INR','Indian rupees',2,0,',','.',true,false],
  ['IQD','Iraqi Dinar','د.ع.‏','IQD','Iraqi dinars',0,0,',','.',true,true],
  ['IRR','Iranian Rial','﷼','IRR','Iranian rials',0,0,',','/',true,true],
  ['Ikr','Icelandic Króna','kr','ISK','Icelandic krónur',0,0,'.',',',false,true],
  ['J$','Jamaican Dollar','$','JMD','Jamaican dollars',2,0,',','.',true,false],
  ['JD','Jordanian Dinar','د.أ.‏','JOD','Jordanian dinars',3,0,',','.',true,true],
  ['¥','Japanese Yen','￥','JPY','Japanese yen',0,0,',','.',true,false],
  ['Ksh','Kenyan Shilling','Ksh','KES','Kenyan shillings',2,0,',','.',true,false],
  ['KHR','Cambodian Riel','៛','KHR','Cambodian riels',2,0,',','.',false,false],
  ['CF','Comorian Franc','FC','KMF','Comorian francs',0,0,',','.',false,false],
  ['₩','South Korean Won','₩','KRW','South Korean won',0,0,',','.',true,false],
  ['KD','Kuwaiti Dinar','د.ك.‏','KWD','Kuwaiti dinars',3,0,',','.',true,true],
  ['KZT','Kazakhstani Tenge','тңг.','KZT','Kazakhstani tenges',2,0,' ','-',true,false],
  ['LB£','Lebanese Pound','ل.ل.‏','LBP','Lebanese pounds',0,0,',','.',true,true],
  ['SLRs','Sri Lankan Rupee','SL Re','LKR','Sri Lankan rupees',2,0,',','.',true,true],
  ['Lt','Lithuanian Litas','Lt','LTL','Lithuanian litai',2,0,'.',' ',true,false],
  ['Ls','Latvian Lats','Ls','LVL','Latvian lati',2,0,'.',' ',true,false],
  ['LD','Libyan Dinar','د.ل.‏','LYD','Libyan dinars',3,0,',','.',true,false],
  ['MAD','Moroccan Dirham','د.م.‏','MAD','Moroccan dirhams',2,0,',','.',true,true],
  ['MDL','Moldovan Leu','MDL','MDL','Moldovan lei',2,0,',','.',false,true],
  ['MGA','Malagasy Ariary','MGA','MGA','Malagasy Ariaries',0,0,',','.',true,false],
  ['MKD','Macedonian Denar','MKD','MKD','Macedonian denari',2,0,'.',',',false,true],
  ['MMK','Myanma Kyat','K','MMK','Myanma kyats',0,0,',','.',true,false],
  ['MOP$','Macanese Pataca','MOP$','MOP','Macanese patacas',2,0,',','.',true,false],
  ['MURs','Mauritian Rupee','MURs','MUR','Mauritian rupees',0,0,',','.',true,false],
  ['MX$','Mexican Peso','$','MXN','Mexican pesos',2,0,',','.',true,false],
  ['RM','Malaysian Ringgit','RM','MYR','Malaysian ringgits',2,0,',','.',true,false],
  ['MTn','Mozambican Metical','MTn','MZN','Mozambican meticals',2,0,',','.',true,false],
  ['N$','Namibian Dollar','N$','NAD','Namibian dollars',2,0,',','.',true,false],
  ['₦','Nigerian Naira','₦','NGN','Nigerian nairas',2,0,',','.',true,false],
  ['C$','Nicaraguan Córdoba','C$','NIO','Nicaraguan córdobas',2,0,',','.',true,true],
  ['Nkr','Norwegian Krone','kr','NOK','Norwegian kroner',2,0,' ',',',true,true],
  ['NPRs','Nepalese Rupee','नेरू','NPR','Nepalese rupees',2,0,',','.',true,false],
  ['NZ$','New Zealand Dollar','$','NZD','New Zealand dollars',2,0,',','.',true,false],
  ['OMR','Omani Rial','ر.ع.‏','OMR','Omani rials',3,0,',','.',true,true],
  ['B/.','Panamanian Balboa','B/.','PAB','Panamanian balboas',2,0,',','.',true,true],
  ['S/.','Peruvian Nuevo Sol','S/.','PEN','Peruvian nuevos soles',2,0,',','.',true,true],
  ['₱','Philippine Peso','₱','PHP','Philippine pesos',2,0,',','.',true,false],
  ['PKRs','Pakistani Rupee','₨','PKR','Pakistani rupees',0,0,',','.',true,false],
  ['zł','Polish Zloty','zł','PLN','Polish zlotys',2,0,' ',',',false,true],
  ['₲','Paraguayan Guarani','₲','PYG','Paraguayan guaranis',0,0,'.',',',true,true],
  ['QR','Qatari Rial','ر.ق.‏','QAR','Qatari rials',2,0,',','.',true,true],
  ['RON','Romanian Leu','RON','RON','Romanian lei',2,0,'.',',',false,true],
  ['din.','Serbian Dinar','дин.','RSD','Serbian dinars',0,0,'.',',',false,true],
  ['RUB','Russian Ruble','руб.','RUB','Russian rubles',2,0,' ',',',false,true],
  ['RWF','Rwandan Franc','FR','RWF','Rwandan francs',0,0,' ',',',true,true],
  ['SR','Saudi Riyal','ر.س.‏','SAR','Saudi riyals',2,0,',','.',true,true],
  ['SDG','Sudanese Pound','SDG','SDG','Sudanese pounds',2,0,',','.',true,false],
  ['Skr','Swedish Krona','kr','SEK','Swedish kronor',2,0,'.',',',false,true],
  ['S$','Singapore Dollar','$','SGD','Singapore dollars',2,0,',','.',true,false],
  ['Ssh','Somali Shilling','Ssh','SOS','Somali shillings',0,0,',','.',true,false],
  ['SY£','Syrian Pound','ل.س.‏','SYP','Syrian pounds',0,0,',','.',true,true],
  ['฿','Thai Baht','฿','THB','Thai baht',2,0,',','.',true,false],
  ['DT','Tunisian Dinar','د.ت.‏','TND','Tunisian dinars',3,0,',','.',true,true],
  ['T$','Tongan Paʻanga','T$','TOP','Tongan paʻanga',2,0,',','.',true,false],
  ['TL','Turkish Lira','TL','TRY','Turkish Lira',2,0,'.',',',false,true],
  ['TT$','Trinidad and Tobago Dollar','$','TTD','Trinidad and Tobago dollars',2,0,',','.',true,false],
  ['NT$','New Taiwan Dollar','NT$','TWD','New Taiwan dollars',2,0,',','.',true,false],
  ['TSh','Tanzanian Shilling','TSh','TZS','Tanzanian shillings',0,0,',','.',true,false],
  ['₴','Ukrainian Hryvnia','₴','UAH','Ukrainian hryvnias',2,0,' ',',',false,false],
  ['USh','Ugandan Shilling','USh','UGX','Ugandan shillings',0,0,',','.',true,false],
  ['$U','Uruguayan Peso','$','UYU','Uruguayan pesos',2,0,'.',',',true,true],
  ['UZS','Uzbekistan Som','UZS','UZS','Uzbekistan som',0,0,' ',',',false,true],
  ['Bs.F.','Venezuelan Bolívar','Bs.F.','VEF','Venezuelan bolívars',2,0,'.',',',true,true],
  ['₫','Vietnamese Dong','₫','VND','Vietnamese dong',0,0,'.',',',false,true],
  ['FCFA','CFA Franc BEAC','FCFA','XAF','CFA francs BEAC',0,0,',','.',false,false],
  ['CFA','CFA Franc BCEAO','CFA','XOF','CFA francs BCEAO',0,0,' ',',',false,false],
  ['YR','Yemeni Rial','ر.ي.‏','YER','Yemeni rials',0,0,',','.',true,true],
  ['R','South African Rand','R','ZAR','South African rand',2,0,' ',',',true,false],
  ['ZK','Zambian Kwacha','ZK','ZMK','Zambian kwachas',2,0,'.',' ',true,false]
]
const INDEX = CurrencyFormats.reduce((acc, a, i) => Object.assign(acc, {[tl(a[0])] : i, [tl(a[1])] : i, [tl(a[3])] : i}), {})

console.log(CurrencyFormats.map(k => k[1]).join(' *'))

// CurrencyFormat: String -> Object
module.exports = compose((k) => (k in INDEX) ? merge(ATTRS, CurrencyFormats[INDEX[k]]) : undefined, tl, toString)